//
//  LocationData.swift
//  SkyPulse
//
//  Created by Salma on 18/05/2024.
//

import Foundation

struct WeatherData :Codable {
    
    var location : String?
    var condition : Condition
    var current : Current
    var forecast : Forecast
}


struct Location: Codable {
    let name: String
    let region: String
    let country: String
    let lat: Double
    let lon: Double
    let tz_id: String
    let localtime_epoch: Int
    let localtime: String
}

struct Condition: Codable {
    let text: String
    let icon: String
    let code: Int
}

struct Current: Codable {
    let last_updated_epoch: Int
    let last_updated: String
    let temp_c: Double
    let temp_f: Double
    let is_day: Int
    let condition: Condition
    let pressure_in: Double
    let humidity: Int
    let feelslike_c: Double
 
}

struct Forecast: Codable {
    let forecastday: [ForecastDay]
}

struct ForecastDay: Codable {
    let date: String
    let date_epoch: Int
    let day: Day
   
}


struct Day: Codable {
    let maxtempC: Double
    let maxtempF: Double
    let mintempC: Double
    let mintempF: Double
    let condition: Condition
}
















/*
 {

   "current": {
     "last_updated_epoch": 1716039000,
     "last_updated": "2024-05-18 16:30",
     "temp_c": 41.7,
     "temp_f": 107,
     "is_day": 1,
     "condition": {
       "text": "Sunny",
       "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
       "code": 1000
     },
     "wind_mph": 16.8,
     "wind_kph": 27,
     "wind_degree": 51,
     "wind_dir": "NE",
     "pressure_mb": 1008,
     "pressure_in": 29.78,
     "precip_mm": 0,
     "precip_in": 0,
     "humidity": 7,
     "cloud": 0,
     "feelslike_c": 42.4,
     "feelslike_f": 108.4,
     "vis_km": 10,
     "vis_miles": 6,
     "uv": 10,
     "gust_mph": 19.3,
     "gust_kph": 31.1
   },
   "forecast": {
     "forecastday": [
       {
         "date": "2024-05-18",
         "date_epoch": 1715990400,
         "day": {
           "maxtemp_c": 41.7,
           "maxtemp_f": 107.1,
           "mintemp_c": 24.8,
           "mintemp_f": 76.7,
           "avgtemp_c": 34.2,
           "avgtemp_f": 93.6,
           "maxwind_mph": 17.9,
           "maxwind_kph": 28.8,
           "totalprecip_mm": 0,
           "totalprecip_in": 0,
           "totalsnow_cm": 0,
           "avgvis_km": 10,
           "avgvis_miles": 6,
           "avghumidity": 14,
           "daily_will_it_rain": 0,
           "daily_chance_of_rain": 0,
           "daily_will_it_snow": 0,
           "daily_chance_of_snow": 0,
           "condition": {
             "text": "Sunny",
             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
             "code": 1000
           },
           "uv": 11
         },
         "astro": {
           "sunrise": "05:17 AM",
           "sunset": "06:44 PM",
           "moonrise": "02:22 PM",
           "moonset": "02:10 AM",
           "moon_phase": "Waxing Gibbous",
           "moon_illumination": 73,
           "is_moon_up": 1,
           "is_sun_up": 0
         },
         "hour": [
           {
             "time_epoch": 1715979600,
             "time": "2024-05-18 00:00",
             "temp_c": 30.6,
             "temp_f": 87.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 16.6,
             "wind_kph": 26.6,
             "wind_degree": 30,
             "wind_dir": "NNE",
             "pressure_mb": 1013,
             "pressure_in": 29.92,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 17,
             "cloud": 0,
             "feelslike_c": 28.4,
             "feelslike_f": 83.1,
             "windchill_c": 30.6,
             "windchill_f": 87.1,
             "heatindex_c": 28.4,
             "heatindex_f": 83.1,
             "dewpoint_c": 2.7,
             "dewpoint_f": 36.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 28.7,
             "gust_kph": 46.3,
             "uv": 1
           },
           {
             "time_epoch": 1715983200,
             "time": "2024-05-18 01:00",
             "temp_c": 29.9,
             "temp_f": 85.9,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 16.1,
             "wind_kph": 25.9,
             "wind_degree": 30,
             "wind_dir": "NNE",
             "pressure_mb": 1013,
             "pressure_in": 29.91,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 18,
             "cloud": 0,
             "feelslike_c": 27.7,
             "feelslike_f": 81.9,
             "windchill_c": 29.9,
             "windchill_f": 85.9,
             "heatindex_c": 27.7,
             "heatindex_f": 81.9,
             "dewpoint_c": 3,
             "dewpoint_f": 37.4,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 28.2,
             "gust_kph": 45.3,
             "uv": 1
           },
           {
             "time_epoch": 1715986800,
             "time": "2024-05-18 02:00",
             "temp_c": 29,
             "temp_f": 84.3,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 15.2,
             "wind_kph": 24.5,
             "wind_degree": 32,
             "wind_dir": "NNE",
             "pressure_mb": 1012,
             "pressure_in": 29.9,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 19,
             "cloud": 0,
             "feelslike_c": 26.9,
             "feelslike_f": 80.4,
             "windchill_c": 29,
             "windchill_f": 84.3,
             "heatindex_c": 26.9,
             "heatindex_f": 80.4,
             "dewpoint_c": 3.4,
             "dewpoint_f": 38,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 27,
             "gust_kph": 43.4,
             "uv": 1
           },
           {
             "time_epoch": 1715990400,
             "time": "2024-05-18 03:00",
             "temp_c": 28,
             "temp_f": 82.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 12.3,
             "wind_kph": 19.8,
             "wind_degree": 36,
             "wind_dir": "NE",
             "pressure_mb": 1012,
             "pressure_in": 29.9,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 21,
             "cloud": 0,
             "feelslike_c": 26.1,
             "feelslike_f": 79,
             "windchill_c": 28,
             "windchill_f": 82.4,
             "heatindex_c": 26.1,
             "heatindex_f": 79,
             "dewpoint_c": 3.7,
             "dewpoint_f": 38.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 22.8,
             "gust_kph": 36.7,
             "uv": 1
           },
           {
             "time_epoch": 1715994000,
             "time": "2024-05-18 04:00",
             "temp_c": 26.3,
             "temp_f": 79.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 7.6,
             "wind_kph": 12.2,
             "wind_degree": 32,
             "wind_dir": "NNE",
             "pressure_mb": 1013,
             "pressure_in": 29.9,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 24,
             "cloud": 0,
             "feelslike_c": 25.1,
             "feelslike_f": 77.1,
             "windchill_c": 26.3,
             "windchill_f": 79.4,
             "heatindex_c": 25.1,
             "heatindex_f": 77.1,
             "dewpoint_c": 4,
             "dewpoint_f": 39.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16,
             "gust_kph": 25.7,
             "uv": 1
           },
           {
             "time_epoch": 1715997600,
             "time": "2024-05-18 05:00",
             "temp_c": 24.8,
             "temp_f": 76.7,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 4.7,
             "wind_kph": 7.6,
             "wind_degree": 22,
             "wind_dir": "NNE",
             "pressure_mb": 1013,
             "pressure_in": 29.9,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 26,
             "cloud": 0,
             "feelslike_c": 24.3,
             "feelslike_f": 75.7,
             "windchill_c": 24.8,
             "windchill_f": 76.7,
             "heatindex_c": 24.3,
             "heatindex_f": 75.7,
             "dewpoint_c": 4.2,
             "dewpoint_f": 39.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 9.9,
             "gust_kph": 15.9,
             "uv": 1
           },
           {
             "time_epoch": 1716001200,
             "time": "2024-05-18 06:00",
             "temp_c": 25.4,
             "temp_f": 77.8,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 3.4,
             "wind_kph": 5.4,
             "wind_degree": 351,
             "wind_dir": "N",
             "pressure_mb": 1013,
             "pressure_in": 29.92,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 26,
             "cloud": 0,
             "feelslike_c": 24.6,
             "feelslike_f": 76.3,
             "windchill_c": 25.4,
             "windchill_f": 77.8,
             "heatindex_c": 24.6,
             "heatindex_f": 76.3,
             "dewpoint_c": 4.3,
             "dewpoint_f": 39.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 7,
             "gust_kph": 11.3,
             "uv": 7
           },
           {
             "time_epoch": 1716004800,
             "time": "2024-05-18 07:00",
             "temp_c": 28.9,
             "temp_f": 84,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 7.4,
             "wind_kph": 11.9,
             "wind_degree": 34,
             "wind_dir": "NE",
             "pressure_mb": 1014,
             "pressure_in": 29.93,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 21,
             "cloud": 0,
             "feelslike_c": 26.8,
             "feelslike_f": 80.3,
             "windchill_c": 28.9,
             "windchill_f": 83.9,
             "heatindex_c": 26.8,
             "heatindex_f": 80.3,
             "dewpoint_c": 4.3,
             "dewpoint_f": 39.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 10.2,
             "gust_kph": 16.5,
             "uv": 7
           },
           {
             "time_epoch": 1716008400,
             "time": "2024-05-18 08:00",
             "temp_c": 31.4,
             "temp_f": 88.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 11,
             "wind_kph": 17.6,
             "wind_degree": 52,
             "wind_dir": "NE",
             "pressure_mb": 1014,
             "pressure_in": 29.94,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 18,
             "cloud": 0,
             "feelslike_c": 29.1,
             "feelslike_f": 84.4,
             "windchill_c": 31.4,
             "windchill_f": 88.4,
             "heatindex_c": 29.1,
             "heatindex_f": 84.4,
             "dewpoint_c": 4.1,
             "dewpoint_f": 39.4,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 12.6,
             "gust_kph": 20.3,
             "uv": 8
           },
           {
             "time_epoch": 1716012000,
             "time": "2024-05-18 09:00",
             "temp_c": 34.1,
             "temp_f": 93.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 12.1,
             "wind_kph": 19.4,
             "wind_degree": 60,
             "wind_dir": "ENE",
             "pressure_mb": 1014,
             "pressure_in": 29.93,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 14,
             "cloud": 0,
             "feelslike_c": 32.2,
             "feelslike_f": 89.9,
             "windchill_c": 34.1,
             "windchill_f": 93.5,
             "heatindex_c": 32.2,
             "heatindex_f": 89.9,
             "dewpoint_c": 3.2,
             "dewpoint_f": 37.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.9,
             "gust_kph": 22.4,
             "uv": 8
           },
           {
             "time_epoch": 1716015600,
             "time": "2024-05-18 10:00",
             "temp_c": 37,
             "temp_f": 98.5,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 12.8,
             "wind_kph": 20.5,
             "wind_degree": 64,
             "wind_dir": "ENE",
             "pressure_mb": 1013,
             "pressure_in": 29.92,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 11,
             "cloud": 0,
             "feelslike_c": 35.7,
             "feelslike_f": 96.2,
             "windchill_c": 37,
             "windchill_f": 98.5,
             "heatindex_c": 35.7,
             "heatindex_f": 96.2,
             "dewpoint_c": 1.6,
             "dewpoint_f": 34.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 14.7,
             "gust_kph": 23.6,
             "uv": 9
           },
           {
             "time_epoch": 1716019200,
             "time": "2024-05-18 11:00",
             "temp_c": 39,
             "temp_f": 102.2,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 13.4,
             "wind_kph": 21.6,
             "wind_degree": 55,
             "wind_dir": "NE",
             "pressure_mb": 1013,
             "pressure_in": 29.91,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 9,
             "cloud": 0,
             "feelslike_c": 38.5,
             "feelslike_f": 101.2,
             "windchill_c": 39,
             "windchill_f": 102.2,
             "heatindex_c": 38.5,
             "heatindex_f": 101.2,
             "dewpoint_c": -0.2,
             "dewpoint_f": 31.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 15.4,
             "gust_kph": 24.8,
             "uv": 9
           },
           {
             "time_epoch": 1716022800,
             "time": "2024-05-18 12:00",
             "temp_c": 40.2,
             "temp_f": 104.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 14.5,
             "wind_kph": 23.4,
             "wind_degree": 50,
             "wind_dir": "NE",
             "pressure_mb": 1012,
             "pressure_in": 29.88,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 40.2,
             "feelslike_f": 104.4,
             "windchill_c": 40.2,
             "windchill_f": 104.4,
             "heatindex_c": 40.2,
             "heatindex_f": 104.4,
             "dewpoint_c": -0.9,
             "dewpoint_f": 30.4,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16.7,
             "gust_kph": 26.9,
             "uv": 10
           },
           {
             "time_epoch": 1716026400,
             "time": "2024-05-18 13:00",
             "temp_c": 41,
             "temp_f": 105.9,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 15.7,
             "wind_kph": 25.2,
             "wind_degree": 49,
             "wind_dir": "NE",
             "pressure_mb": 1011,
             "pressure_in": 29.86,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 41.5,
             "feelslike_f": 106.7,
             "windchill_c": 41.1,
             "windchill_f": 105.9,
             "heatindex_c": 41.5,
             "heatindex_f": 106.7,
             "dewpoint_c": -1.3,
             "dewpoint_f": 29.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 18,
             "gust_kph": 29,
             "uv": 10
           },
           {
             "time_epoch": 1716030000,
             "time": "2024-05-18 14:00",
             "temp_c": 41.4,
             "temp_f": 106.6,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.8,
             "wind_kph": 27,
             "wind_degree": 51,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 42.1,
             "feelslike_f": 107.7,
             "windchill_c": 41.4,
             "windchill_f": 106.6,
             "heatindex_c": 42.1,
             "heatindex_f": 107.7,
             "dewpoint_c": -1.3,
             "dewpoint_f": 29.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 19.3,
             "gust_kph": 31.1,
             "uv": 10
           },
           {
             "time_epoch": 1716033600,
             "time": "2024-05-18 15:00",
             "temp_c": 41.7,
             "temp_f": 107.1,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.3,
             "wind_kph": 26.3,
             "wind_degree": 53,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 42.5,
             "feelslike_f": 108.5,
             "windchill_c": 41.7,
             "windchill_f": 107.1,
             "heatindex_c": 42.5,
             "heatindex_f": 108.5,
             "dewpoint_c": -1.8,
             "dewpoint_f": 28.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 18.8,
             "gust_kph": 30.2,
             "uv": 10
           },
           {
             "time_epoch": 1716037200,
             "time": "2024-05-18 16:00",
             "temp_c": 41.7,
             "temp_f": 107,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.8,
             "wind_kph": 27,
             "wind_degree": 51,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.78,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 42.4,
             "feelslike_f": 108.4,
             "windchill_c": 41.7,
             "windchill_f": 107,
             "heatindex_c": 42.4,
             "heatindex_f": 108.4,
             "dewpoint_c": -1.9,
             "dewpoint_f": 28.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 19.3,
             "gust_kph": 31.1,
             "uv": 10
           },
           {
             "time_epoch": 1716040800,
             "time": "2024-05-18 17:00",
             "temp_c": 41.3,
             "temp_f": 106.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 13.6,
             "wind_kph": 22,
             "wind_degree": 47,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.77,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 6,
             "cloud": 0,
             "feelslike_c": 41.9,
             "feelslike_f": 107.5,
             "windchill_c": 41.3,
             "windchill_f": 106.4,
             "heatindex_c": 41.9,
             "heatindex_f": 107.5,
             "dewpoint_c": -2.4,
             "dewpoint_f": 27.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16.1,
             "gust_kph": 26,
             "uv": 10
           },
           {
             "time_epoch": 1716044400,
             "time": "2024-05-18 18:00",
             "temp_c": 39.6,
             "temp_f": 103.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 9.4,
             "wind_kph": 15.1,
             "wind_degree": 40,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.77,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 39.4,
             "feelslike_f": 102.9,
             "windchill_c": 39.6,
             "windchill_f": 103.4,
             "heatindex_c": 39.4,
             "heatindex_f": 102.9,
             "dewpoint_c": -2.6,
             "dewpoint_f": 27.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 15.4,
             "gust_kph": 24.7,
             "uv": 9
           },
           {
             "time_epoch": 1716048000,
             "time": "2024-05-18 19:00",
             "temp_c": 35.8,
             "temp_f": 96.5,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 7.6,
             "wind_kph": 12.2,
             "wind_degree": 66,
             "wind_dir": "ENE",
             "pressure_mb": 1008,
             "pressure_in": 29.78,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 9,
             "cloud": 0,
             "feelslike_c": 34.2,
             "feelslike_f": 93.6,
             "windchill_c": 35.9,
             "windchill_f": 96.5,
             "heatindex_c": 34.2,
             "heatindex_f": 93.6,
             "dewpoint_c": -2.6,
             "dewpoint_f": 27.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16,
             "gust_kph": 25.7,
             "uv": 1
           },
           {
             "time_epoch": 1716051600,
             "time": "2024-05-18 20:00",
             "temp_c": 33.4,
             "temp_f": 92.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 5.4,
             "wind_kph": 8.6,
             "wind_degree": 60,
             "wind_dir": "ENE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 10,
             "cloud": 0,
             "feelslike_c": 31.3,
             "feelslike_f": 88.4,
             "windchill_c": 33.4,
             "windchill_f": 92.1,
             "heatindex_c": 31.3,
             "heatindex_f": 88.4,
             "dewpoint_c": -2.5,
             "dewpoint_f": 27.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 11.3,
             "gust_kph": 18.1,
             "uv": 1
           },
           {
             "time_epoch": 1716055200,
             "time": "2024-05-18 21:00",
             "temp_c": 33.3,
             "temp_f": 92,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 7.4,
             "wind_kph": 11.9,
             "wind_degree": 5,
             "wind_dir": "N",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 10,
             "cloud": 0,
             "feelslike_c": 31.2,
             "feelslike_f": 88.2,
             "windchill_c": 33.3,
             "windchill_f": 92,
             "heatindex_c": 31.2,
             "heatindex_f": 88.2,
             "dewpoint_c": -2,
             "dewpoint_f": 28.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 15.5,
             "gust_kph": 24.9,
             "uv": 1
           },
           {
             "time_epoch": 1716058800,
             "time": "2024-05-18 22:00",
             "temp_c": 33.3,
             "temp_f": 92,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 12.1,
             "wind_kph": 19.4,
             "wind_degree": 21,
             "wind_dir": "NNE",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 12,
             "cloud": 0,
             "feelslike_c": 31.2,
             "feelslike_f": 88.2,
             "windchill_c": 33.3,
             "windchill_f": 92,
             "heatindex_c": 31.2,
             "heatindex_f": 88.2,
             "dewpoint_c": 0,
             "dewpoint_f": 32,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 25.4,
             "gust_kph": 40.8,
             "uv": 1
           },
           {
             "time_epoch": 1716062400,
             "time": "2024-05-18 23:00",
             "temp_c": 33.6,
             "temp_f": 92.5,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 17.9,
             "wind_kph": 28.8,
             "wind_degree": 32,
             "wind_dir": "NNE",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 31.5,
             "feelslike_f": 88.8,
             "windchill_c": 33.6,
             "windchill_f": 92.5,
             "heatindex_c": 31.5,
             "heatindex_f": 88.8,
             "dewpoint_c": 1,
             "dewpoint_f": 33.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 32.6,
             "gust_kph": 52.5,
             "uv": 1
           }
         ]
       },
       {
         "date": "2024-05-19",
         "date_epoch": 1716076800,
         "day": {
           "maxtemp_c": 42.3,
           "maxtemp_f": 108.2,
           "mintemp_c": 28.3,
           "mintemp_f": 82.9,
           "avgtemp_c": 36.1,
           "avgtemp_f": 96.9,
           "maxwind_mph": 19.7,
           "maxwind_kph": 31.7,
           "totalprecip_mm": 0,
           "totalprecip_in": 0,
           "totalsnow_cm": 0,
           "avgvis_km": 10,
           "avgvis_miles": 6,
           "avghumidity": 12,
           "daily_will_it_rain": 0,
           "daily_chance_of_rain": 0,
           "daily_will_it_snow": 0,
           "daily_chance_of_snow": 0,
           "condition": {
             "text": "Sunny",
             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
             "code": 1000
           },
           "uv": 9
         },
         "astro": {
           "sunrise": "05:17 AM",
           "sunset": "06:44 PM",
           "moonrise": "03:13 PM",
           "moonset": "02:37 AM",
           "moon_phase": "Waxing Gibbous",
           "moon_illumination": 81,
           "is_moon_up": 1,
           "is_sun_up": 0
         },
         "hour": [
           {
             "time_epoch": 1716066000,
             "time": "2024-05-19 00:00",
             "temp_c": 33.4,
             "temp_f": 92.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 19.7,
             "wind_kph": 31.7,
             "wind_degree": 39,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 31.3,
             "feelslike_f": 88.3,
             "windchill_c": 33.4,
             "windchill_f": 92.1,
             "heatindex_c": 31.3,
             "heatindex_f": 88.3,
             "dewpoint_c": 1.1,
             "dewpoint_f": 34.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 34.8,
             "gust_kph": 55.9,
             "uv": 1
           },
           {
             "time_epoch": 1716069600,
             "time": "2024-05-19 01:00",
             "temp_c": 32.9,
             "temp_f": 91.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 19.5,
             "wind_kph": 31.3,
             "wind_degree": 45,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 30.7,
             "feelslike_f": 87.2,
             "windchill_c": 32.9,
             "windchill_f": 91.1,
             "heatindex_c": 30.7,
             "heatindex_f": 87.2,
             "dewpoint_c": 1.2,
             "dewpoint_f": 34.2,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 35.2,
             "gust_kph": 56.7,
             "uv": 1
           },
           {
             "time_epoch": 1716073200,
             "time": "2024-05-19 02:00",
             "temp_c": 31.8,
             "temp_f": 89.3,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 17.4,
             "wind_kph": 28.1,
             "wind_degree": 44,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 14,
             "cloud": 0,
             "feelslike_c": 29.6,
             "feelslike_f": 85.3,
             "windchill_c": 31.8,
             "windchill_f": 89.3,
             "heatindex_c": 29.6,
             "heatindex_f": 85.3,
             "dewpoint_c": 1.3,
             "dewpoint_f": 34.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 33.1,
             "gust_kph": 53.2,
             "uv": 1
           },
           {
             "time_epoch": 1716076800,
             "time": "2024-05-19 03:00",
             "temp_c": 30.8,
             "temp_f": 87.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 14.3,
             "wind_kph": 23,
             "wind_degree": 43,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.81,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 15,
             "cloud": 0,
             "feelslike_c": 28.6,
             "feelslike_f": 83.4,
             "windchill_c": 30.8,
             "windchill_f": 87.4,
             "heatindex_c": 28.6,
             "heatindex_f": 83.4,
             "dewpoint_c": 1.4,
             "dewpoint_f": 34.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 27.9,
             "gust_kph": 44.9,
             "uv": 1
           },
           {
             "time_epoch": 1716080400,
             "time": "2024-05-19 04:00",
             "temp_c": 29.7,
             "temp_f": 85.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 10.5,
             "wind_kph": 16.9,
             "wind_degree": 53,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 17,
             "cloud": 0,
             "feelslike_c": 27.5,
             "feelslike_f": 81.4,
             "windchill_c": 29.7,
             "windchill_f": 85.4,
             "heatindex_c": 27.5,
             "heatindex_f": 81.4,
             "dewpoint_c": 1.8,
             "dewpoint_f": 35.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 22.1,
             "gust_kph": 35.5,
             "uv": 1
           },
           {
             "time_epoch": 1716084000,
             "time": "2024-05-19 05:00",
             "temp_c": 28.3,
             "temp_f": 82.9,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 7.2,
             "wind_kph": 11.5,
             "wind_degree": 63,
             "wind_dir": "ENE",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 18,
             "cloud": 0,
             "feelslike_c": 26.2,
             "feelslike_f": 79.2,
             "windchill_c": 28.3,
             "windchill_f": 82.9,
             "heatindex_c": 26.2,
             "heatindex_f": 79.2,
             "dewpoint_c": 2,
             "dewpoint_f": 35.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 15,
             "gust_kph": 24.2,
             "uv": 1
           },
           {
             "time_epoch": 1716087600,
             "time": "2024-05-19 06:00",
             "temp_c": 28.6,
             "temp_f": 83.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 4.9,
             "wind_kph": 7.9,
             "wind_degree": 73,
             "wind_dir": "ENE",
             "pressure_mb": 1011,
             "pressure_in": 29.84,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 18,
             "cloud": 0,
             "feelslike_c": 26.5,
             "feelslike_f": 79.7,
             "windchill_c": 28.6,
             "windchill_f": 83.4,
             "heatindex_c": 26.5,
             "heatindex_f": 79.7,
             "dewpoint_c": 2.1,
             "dewpoint_f": 35.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 10.3,
             "gust_kph": 16.6,
             "uv": 7
           },
           {
             "time_epoch": 1716091200,
             "time": "2024-05-19 07:00",
             "temp_c": 31.9,
             "temp_f": 89.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 7.6,
             "wind_kph": 12.2,
             "wind_degree": 62,
             "wind_dir": "ENE",
             "pressure_mb": 1011,
             "pressure_in": 29.86,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 15,
             "cloud": 0,
             "feelslike_c": 29.7,
             "feelslike_f": 85.4,
             "windchill_c": 31.9,
             "windchill_f": 89.4,
             "heatindex_c": 29.7,
             "heatindex_f": 85.4,
             "dewpoint_c": 2,
             "dewpoint_f": 35.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 11.1,
             "gust_kph": 17.9,
             "uv": 8
           },
           {
             "time_epoch": 1716094800,
             "time": "2024-05-19 08:00",
             "temp_c": 34.8,
             "temp_f": 94.7,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 14.1,
             "wind_kph": 22.7,
             "wind_degree": 53,
             "wind_dir": "NE",
             "pressure_mb": 1011,
             "pressure_in": 29.86,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 33,
             "feelslike_f": 91.4,
             "windchill_c": 34.8,
             "windchill_f": 94.7,
             "heatindex_c": 33,
             "heatindex_f": 91.4,
             "dewpoint_c": 2.2,
             "dewpoint_f": 35.9,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16.2,
             "gust_kph": 26.1,
             "uv": 8
           },
           {
             "time_epoch": 1716098400,
             "time": "2024-05-19 09:00",
             "temp_c": 36.9,
             "temp_f": 98.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 18.1,
             "wind_kph": 29.2,
             "wind_degree": 51,
             "wind_dir": "NE",
             "pressure_mb": 1011,
             "pressure_in": 29.86,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 11,
             "cloud": 6,
             "feelslike_c": 35.6,
             "feelslike_f": 96,
             "windchill_c": 36.9,
             "windchill_f": 98.4,
             "heatindex_c": 35.6,
             "heatindex_f": 96,
             "dewpoint_c": 2.1,
             "dewpoint_f": 35.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 20.8,
             "gust_kph": 33.6,
             "uv": 9
           },
           {
             "time_epoch": 1716102000,
             "time": "2024-05-19 10:00",
             "temp_c": 38.9,
             "temp_f": 102.1,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 19.5,
             "wind_kph": 31.3,
             "wind_degree": 51,
             "wind_dir": "NE",
             "pressure_mb": 1011,
             "pressure_in": 29.86,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 10,
             "cloud": 16,
             "feelslike_c": 38.4,
             "feelslike_f": 101,
             "windchill_c": 38.9,
             "windchill_f": 102.1,
             "heatindex_c": 38.4,
             "heatindex_f": 101,
             "dewpoint_c": 2.1,
             "dewpoint_f": 35.9,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 22.4,
             "gust_kph": 36,
             "uv": 9
           },
           {
             "time_epoch": 1716105600,
             "time": "2024-05-19 11:00",
             "temp_c": 40.4,
             "temp_f": 104.7,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 19,
             "wind_kph": 30.6,
             "wind_degree": 48,
             "wind_dir": "NE",
             "pressure_mb": 1011,
             "pressure_in": 29.84,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 9,
             "cloud": 9,
             "feelslike_c": 40.5,
             "feelslike_f": 104.9,
             "windchill_c": 40.4,
             "windchill_f": 104.7,
             "heatindex_c": 40.5,
             "heatindex_f": 104.9,
             "dewpoint_c": 1.6,
             "dewpoint_f": 35,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 21.9,
             "gust_kph": 35.2,
             "uv": 10
           },
           {
             "time_epoch": 1716109200,
             "time": "2024-05-19 12:00",
             "temp_c": 41.3,
             "temp_f": 106.3,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 18.1,
             "wind_kph": 29.2,
             "wind_degree": 42,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 2,
             "feelslike_c": 41.8,
             "feelslike_f": 107.3,
             "windchill_c": 41.3,
             "windchill_f": 106.3,
             "heatindex_c": 41.8,
             "heatindex_f": 107.3,
             "dewpoint_c": 1.2,
             "dewpoint_f": 34.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 20.8,
             "gust_kph": 33.6,
             "uv": 10
           },
           {
             "time_epoch": 1716112800,
             "time": "2024-05-19 13:00",
             "temp_c": 41.8,
             "temp_f": 107.2,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.3,
             "wind_kph": 26.3,
             "wind_degree": 37,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 42.7,
             "feelslike_f": 108.8,
             "windchill_c": 41.8,
             "windchill_f": 107.2,
             "heatindex_c": 42.7,
             "heatindex_f": 108.8,
             "dewpoint_c": 0.7,
             "dewpoint_f": 33.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 18.8,
             "gust_kph": 30.2,
             "uv": 10
           },
           {
             "time_epoch": 1716116400,
             "time": "2024-05-19 14:00",
             "temp_c": 42.3,
             "temp_f": 108.1,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.6,
             "wind_kph": 26.6,
             "wind_degree": 36,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.77,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 43.4,
             "feelslike_f": 110.1,
             "windchill_c": 42.3,
             "windchill_f": 108.1,
             "heatindex_c": 43.4,
             "heatindex_f": 110.1,
             "dewpoint_c": 0.7,
             "dewpoint_f": 33.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 19,
             "gust_kph": 30.6,
             "uv": 10
           },
           {
             "time_epoch": 1716120000,
             "time": "2024-05-19 15:00",
             "temp_c": 42.3,
             "temp_f": 108.2,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.8,
             "wind_kph": 27,
             "wind_degree": 36,
             "wind_dir": "NE",
             "pressure_mb": 1007,
             "pressure_in": 29.75,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 43.5,
             "feelslike_f": 110.3,
             "windchill_c": 42.3,
             "windchill_f": 108.2,
             "heatindex_c": 43.5,
             "heatindex_f": 110.3,
             "dewpoint_c": 0.4,
             "dewpoint_f": 32.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 19.3,
             "gust_kph": 31.1,
             "uv": 10
           },
           {
             "time_epoch": 1716123600,
             "time": "2024-05-19 16:00",
             "temp_c": 42,
             "temp_f": 107.6,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 17,
             "wind_kph": 27.4,
             "wind_degree": 36,
             "wind_dir": "NE",
             "pressure_mb": 1007,
             "pressure_in": 29.73,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 43,
             "feelslike_f": 109.4,
             "windchill_c": 42,
             "windchill_f": 107.6,
             "heatindex_c": 43,
             "heatindex_f": 109.4,
             "dewpoint_c": 0.4,
             "dewpoint_f": 32.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 19.6,
             "gust_kph": 31.5,
             "uv": 10
           },
           {
             "time_epoch": 1716127200,
             "time": "2024-05-19 17:00",
             "temp_c": 41.4,
             "temp_f": 106.5,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 17.4,
             "wind_kph": 28.1,
             "wind_degree": 33,
             "wind_dir": "NNE",
             "pressure_mb": 1007,
             "pressure_in": 29.73,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 1,
             "feelslike_c": 42.1,
             "feelslike_f": 107.7,
             "windchill_c": 41.4,
             "windchill_f": 106.5,
             "heatindex_c": 42.1,
             "heatindex_f": 107.7,
             "dewpoint_c": 0.3,
             "dewpoint_f": 32.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 20.4,
             "gust_kph": 32.8,
             "uv": 10
           },
           {
             "time_epoch": 1716130800,
             "time": "2024-05-19 18:00",
             "temp_c": 40,
             "temp_f": 104,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 16.8,
             "wind_kph": 27,
             "wind_degree": 31,
             "wind_dir": "NNE",
             "pressure_mb": 1007,
             "pressure_in": 29.74,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 9,
             "cloud": 5,
             "feelslike_c": 39.9,
             "feelslike_f": 103.8,
             "windchill_c": 40,
             "windchill_f": 104,
             "heatindex_c": 39.9,
             "heatindex_f": 103.8,
             "dewpoint_c": 0.9,
             "dewpoint_f": 33.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 24,
             "gust_kph": 38.6,
             "uv": 9
           },
           {
             "time_epoch": 1716134400,
             "time": "2024-05-19 19:00",
             "temp_c": 37.1,
             "temp_f": 98.8,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 14.3,
             "wind_kph": 23,
             "wind_degree": 32,
             "wind_dir": "NNE",
             "pressure_mb": 1008,
             "pressure_in": 29.76,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 11,
             "cloud": 0,
             "feelslike_c": 35.9,
             "feelslike_f": 96.5,
             "windchill_c": 37.1,
             "windchill_f": 98.8,
             "heatindex_c": 35.9,
             "heatindex_f": 96.5,
             "dewpoint_c": 1.2,
             "dewpoint_f": 34.2,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 27.1,
             "gust_kph": 43.7,
             "uv": 1
           },
           {
             "time_epoch": 1716138000,
             "time": "2024-05-19 20:00",
             "temp_c": 35.9,
             "temp_f": 96.6,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 15.4,
             "wind_kph": 24.8,
             "wind_degree": 38,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.78,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 12,
             "cloud": 0,
             "feelslike_c": 34.3,
             "feelslike_f": 93.7,
             "windchill_c": 35.9,
             "windchill_f": 96.6,
             "heatindex_c": 34.3,
             "heatindex_f": 93.7,
             "dewpoint_c": 1.7,
             "dewpoint_f": 35.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 29.3,
             "gust_kph": 47.1,
             "uv": 1
           },
           {
             "time_epoch": 1716141600,
             "time": "2024-05-19 21:00",
             "temp_c": 35.3,
             "temp_f": 95.6,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 17.4,
             "wind_kph": 28.1,
             "wind_degree": 43,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 12,
             "cloud": 0,
             "feelslike_c": 33.6,
             "feelslike_f": 92.4,
             "windchill_c": 35.3,
             "windchill_f": 95.6,
             "heatindex_c": 33.6,
             "heatindex_f": 92.4,
             "dewpoint_c": 1.9,
             "dewpoint_f": 35.4,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 31.3,
             "gust_kph": 50.4,
             "uv": 1
           },
           {
             "time_epoch": 1716145200,
             "time": "2024-05-19 22:00",
             "temp_c": 34.5,
             "temp_f": 94.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 15.2,
             "wind_kph": 24.5,
             "wind_degree": 48,
             "wind_dir": "NE",
             "pressure_mb": 1010,
             "pressure_in": 29.81,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 32.6,
             "feelslike_f": 90.7,
             "windchill_c": 34.5,
             "windchill_f": 94.2,
             "heatindex_c": 32.6,
             "heatindex_f": 90.7,
             "dewpoint_c": 2.4,
             "dewpoint_f": 36.2,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 28.5,
             "gust_kph": 45.9,
             "uv": 1
           },
           {
             "time_epoch": 1716148800,
             "time": "2024-05-19 23:00",
             "temp_c": 33.2,
             "temp_f": 91.7,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 11.2,
             "wind_kph": 18,
             "wind_degree": 53,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.81,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 15,
             "cloud": 0,
             "feelslike_c": 31,
             "feelslike_f": 87.9,
             "windchill_c": 33.2,
             "windchill_f": 91.7,
             "heatindex_c": 31,
             "heatindex_f": 87.9,
             "dewpoint_c": 2.8,
             "dewpoint_f": 37.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 23.5,
             "gust_kph": 37.8,
             "uv": 1
           }
         ]
       },
       {
         "date": "2024-05-20",
         "date_epoch": 1716163200,
         "day": {
           "maxtemp_c": 43,
           "maxtemp_f": 109.4,
           "mintemp_c": 27.2,
           "mintemp_f": 81,
           "avgtemp_c": 35.8,
           "avgtemp_f": 96.5,
           "maxwind_mph": 12.5,
           "maxwind_kph": 20.2,
           "totalprecip_mm": 0,
           "totalprecip_in": 0,
           "totalsnow_cm": 0,
           "avgvis_km": 10,
           "avgvis_miles": 6,
           "avghumidity": 12,
           "daily_will_it_rain": 0,
           "daily_chance_of_rain": 0,
           "daily_will_it_snow": 0,
           "daily_chance_of_snow": 0,
           "condition": {
             "text": "Sunny",
             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
             "code": 1000
           },
           "uv": 10
         },
         "astro": {
           "sunrise": "05:17 AM",
           "sunset": "06:45 PM",
           "moonrise": "04:04 PM",
           "moonset": "03:06 AM",
           "moon_phase": "Waxing Gibbous",
           "moon_illumination": 88,
           "is_moon_up": 1,
           "is_sun_up": 0
         },
         "hour": [
           {
             "time_epoch": 1716152400,
             "time": "2024-05-20 00:00",
             "temp_c": 32.5,
             "temp_f": 90.5,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 10.3,
             "wind_kph": 16.6,
             "wind_degree": 49,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 16,
             "cloud": 1,
             "feelslike_c": 30.3,
             "feelslike_f": 86.5,
             "windchill_c": 32.5,
             "windchill_f": 90.5,
             "heatindex_c": 30.3,
             "heatindex_f": 86.5,
             "dewpoint_c": 3.1,
             "dewpoint_f": 37.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 21.6,
             "gust_kph": 34.8,
             "uv": 1
           },
           {
             "time_epoch": 1716156000,
             "time": "2024-05-20 01:00",
             "temp_c": 31.3,
             "temp_f": 88.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 7.8,
             "wind_kph": 12.6,
             "wind_degree": 44,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.79,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 17,
             "cloud": 0,
             "feelslike_c": 29.1,
             "feelslike_f": 84.3,
             "windchill_c": 31.3,
             "windchill_f": 88.4,
             "heatindex_c": 29.1,
             "heatindex_f": 84.3,
             "dewpoint_c": 3.2,
             "dewpoint_f": 37.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 16.4,
             "gust_kph": 26.5,
             "uv": 1
           },
           {
             "time_epoch": 1716159600,
             "time": "2024-05-20 02:00",
             "temp_c": 29.8,
             "temp_f": 85.7,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 5.1,
             "wind_kph": 8.3,
             "wind_degree": 47,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.79,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 18,
             "cloud": 0,
             "feelslike_c": 27.6,
             "feelslike_f": 81.7,
             "windchill_c": 29.8,
             "windchill_f": 85.7,
             "heatindex_c": 27.6,
             "heatindex_f": 81.7,
             "dewpoint_c": 3.3,
             "dewpoint_f": 38,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 10.8,
             "gust_kph": 17.4,
             "uv": 1
           },
           {
             "time_epoch": 1716163200,
             "time": "2024-05-20 03:00",
             "temp_c": 28.6,
             "temp_f": 83.5,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 3.8,
             "wind_kph": 6.1,
             "wind_degree": 46,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.79,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 20,
             "cloud": 0,
             "feelslike_c": 26.5,
             "feelslike_f": 79.8,
             "windchill_c": 28.6,
             "windchill_f": 83.5,
             "heatindex_c": 26.5,
             "heatindex_f": 79.8,
             "dewpoint_c": 3.5,
             "dewpoint_f": 38.2,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 8,
             "gust_kph": 12.9,
             "uv": 1
           },
           {
             "time_epoch": 1716166800,
             "time": "2024-05-20 04:00",
             "temp_c": 27.8,
             "temp_f": 82.1,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 2.9,
             "wind_kph": 4.7,
             "wind_degree": 46,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.79,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 21,
             "cloud": 0,
             "feelslike_c": 26,
             "feelslike_f": 78.7,
             "windchill_c": 27.8,
             "windchill_f": 82.1,
             "heatindex_c": 26,
             "heatindex_f": 78.7,
             "dewpoint_c": 3.5,
             "dewpoint_f": 38.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 6.1,
             "gust_kph": 9.8,
             "uv": 1
           },
           {
             "time_epoch": 1716170400,
             "time": "2024-05-20 05:00",
             "temp_c": 27.2,
             "temp_f": 81,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 2.9,
             "wind_kph": 4.7,
             "wind_degree": 57,
             "wind_dir": "ENE",
             "pressure_mb": 1009,
             "pressure_in": 29.8,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 22,
             "cloud": 0,
             "feelslike_c": 25.6,
             "feelslike_f": 78,
             "windchill_c": 27.2,
             "windchill_f": 81,
             "heatindex_c": 25.6,
             "heatindex_f": 78,
             "dewpoint_c": 3.5,
             "dewpoint_f": 38.2,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 6.1,
             "gust_kph": 9.8,
             "uv": 1
           },
           {
             "time_epoch": 1716174000,
             "time": "2024-05-20 06:00",
             "temp_c": 28.4,
             "temp_f": 83.1,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 2.5,
             "wind_kph": 4,
             "wind_degree": 71,
             "wind_dir": "ENE",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 20,
             "cloud": 0,
             "feelslike_c": 26.4,
             "feelslike_f": 79.4,
             "windchill_c": 28.4,
             "windchill_f": 83.1,
             "heatindex_c": 26.4,
             "heatindex_f": 79.4,
             "dewpoint_c": 3.4,
             "dewpoint_f": 38.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 5.2,
             "gust_kph": 8.3,
             "uv": 7
           },
           {
             "time_epoch": 1716177600,
             "time": "2024-05-20 07:00",
             "temp_c": 31.9,
             "temp_f": 89.5,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 2.9,
             "wind_kph": 4.7,
             "wind_degree": 93,
             "wind_dir": "E",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 16,
             "cloud": 0,
             "feelslike_c": 29.7,
             "feelslike_f": 85.5,
             "windchill_c": 31.9,
             "windchill_f": 89.5,
             "heatindex_c": 29.7,
             "heatindex_f": 85.5,
             "dewpoint_c": 3.4,
             "dewpoint_f": 38.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 4.4,
             "gust_kph": 7.1,
             "uv": 8
           },
           {
             "time_epoch": 1716181200,
             "time": "2024-05-20 08:00",
             "temp_c": 34.3,
             "temp_f": 93.8,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 3.8,
             "wind_kph": 6.1,
             "wind_degree": 89,
             "wind_dir": "E",
             "pressure_mb": 1010,
             "pressure_in": 29.84,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 14,
             "cloud": 0,
             "feelslike_c": 32.4,
             "feelslike_f": 90.3,
             "windchill_c": 34.3,
             "windchill_f": 93.8,
             "heatindex_c": 32.4,
             "heatindex_f": 90.3,
             "dewpoint_c": 3.1,
             "dewpoint_f": 37.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 4.6,
             "gust_kph": 7.4,
             "uv": 8
           },
           {
             "time_epoch": 1716184800,
             "time": "2024-05-20 09:00",
             "temp_c": 37,
             "temp_f": 98.5,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 4.9,
             "wind_kph": 7.9,
             "wind_degree": 87,
             "wind_dir": "E",
             "pressure_mb": 1010,
             "pressure_in": 29.83,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 12,
             "cloud": 0,
             "feelslike_c": 35.7,
             "feelslike_f": 96.2,
             "windchill_c": 37,
             "windchill_f": 98.5,
             "heatindex_c": 35.7,
             "heatindex_f": 96.2,
             "dewpoint_c": 2.4,
             "dewpoint_f": 36.4,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 5.7,
             "gust_kph": 9.1,
             "uv": 9
           },
           {
             "time_epoch": 1716188400,
             "time": "2024-05-20 10:00",
             "temp_c": 39.1,
             "temp_f": 102.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 5.8,
             "wind_kph": 9.4,
             "wind_degree": 89,
             "wind_dir": "E",
             "pressure_mb": 1010,
             "pressure_in": 29.82,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 9,
             "cloud": 0,
             "feelslike_c": 38.7,
             "feelslike_f": 101.6,
             "windchill_c": 39.1,
             "windchill_f": 102.5,
             "heatindex_c": 38.7,
             "heatindex_f": 101.6,
             "dewpoint_c": 0.7,
             "dewpoint_f": 33.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 6.7,
             "gust_kph": 10.8,
             "uv": 9
           },
           {
             "time_epoch": 1716192000,
             "time": "2024-05-20 11:00",
             "temp_c": 40.6,
             "temp_f": 105.1,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 5.6,
             "wind_kph": 9,
             "wind_degree": 79,
             "wind_dir": "E",
             "pressure_mb": 1009,
             "pressure_in": 29.81,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 40.9,
             "feelslike_f": 105.5,
             "windchill_c": 40.6,
             "windchill_f": 105.1,
             "heatindex_c": 40.9,
             "heatindex_f": 105.5,
             "dewpoint_c": -0.1,
             "dewpoint_f": 31.8,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 6.4,
             "gust_kph": 10.4,
             "uv": 10
           },
           {
             "time_epoch": 1716195600,
             "time": "2024-05-20 12:00",
             "temp_c": 41.9,
             "temp_f": 107.5,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 8.3,
             "wind_kph": 13.3,
             "wind_degree": 50,
             "wind_dir": "NE",
             "pressure_mb": 1009,
             "pressure_in": 29.79,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 42.9,
             "feelslike_f": 109.2,
             "windchill_c": 42,
             "windchill_f": 107.5,
             "heatindex_c": 42.9,
             "heatindex_f": 109.2,
             "dewpoint_c": -0.8,
             "dewpoint_f": 30.5,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 9.5,
             "gust_kph": 15.3,
             "uv": 10
           },
           {
             "time_epoch": 1716199200,
             "time": "2024-05-20 13:00",
             "temp_c": 42.8,
             "temp_f": 109,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 11.4,
             "wind_kph": 18.4,
             "wind_degree": 39,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.77,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 6,
             "cloud": 0,
             "feelslike_c": 44.2,
             "feelslike_f": 111.5,
             "windchill_c": 42.8,
             "windchill_f": 109,
             "heatindex_c": 44.2,
             "heatindex_f": 111.5,
             "dewpoint_c": -1.3,
             "dewpoint_f": 29.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.1,
             "gust_kph": 21.1,
             "uv": 10
           },
           {
             "time_epoch": 1716202800,
             "time": "2024-05-20 14:00",
             "temp_c": 43,
             "temp_f": 109.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 11.4,
             "wind_kph": 18.4,
             "wind_degree": 35,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.75,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 6,
             "cloud": 0,
             "feelslike_c": 44.6,
             "feelslike_f": 112.2,
             "windchill_c": 43,
             "windchill_f": 109.4,
             "heatindex_c": 44.6,
             "heatindex_f": 112.2,
             "dewpoint_c": -1.1,
             "dewpoint_f": 30,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.1,
             "gust_kph": 21.1,
             "uv": 10
           },
           {
             "time_epoch": 1716206400,
             "time": "2024-05-20 15:00",
             "temp_c": 43,
             "temp_f": 109.4,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 11.9,
             "wind_kph": 19.1,
             "wind_degree": 33,
             "wind_dir": "NNE",
             "pressure_mb": 1007,
             "pressure_in": 29.73,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 6,
             "cloud": 0,
             "feelslike_c": 44.6,
             "feelslike_f": 112.3,
             "windchill_c": 43,
             "windchill_f": 109.4,
             "heatindex_c": 44.6,
             "heatindex_f": 112.3,
             "dewpoint_c": -1.1,
             "dewpoint_f": 30,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.6,
             "gust_kph": 22,
             "uv": 10
           },
           {
             "time_epoch": 1716210000,
             "time": "2024-05-20 16:00",
             "temp_c": 42.7,
             "temp_f": 108.9,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 12.5,
             "wind_kph": 20.2,
             "wind_degree": 24,
             "wind_dir": "NNE",
             "pressure_mb": 1007,
             "pressure_in": 29.72,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 44.1,
             "feelslike_f": 111.4,
             "windchill_c": 42.7,
             "windchill_f": 108.9,
             "heatindex_c": 44.1,
             "heatindex_f": 111.4,
             "dewpoint_c": -0.7,
             "dewpoint_f": 30.7,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 14.4,
             "gust_kph": 23.2,
             "uv": 10
           },
           {
             "time_epoch": 1716213600,
             "time": "2024-05-20 17:00",
             "temp_c": 42.1,
             "temp_f": 107.7,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 11.9,
             "wind_kph": 19.1,
             "wind_degree": 11,
             "wind_dir": "NNE",
             "pressure_mb": 1007,
             "pressure_in": 29.72,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 7,
             "cloud": 0,
             "feelslike_c": 43.1,
             "feelslike_f": 109.5,
             "windchill_c": 42.1,
             "windchill_f": 107.7,
             "heatindex_c": 43.1,
             "heatindex_f": 109.5,
             "dewpoint_c": -0.6,
             "dewpoint_f": 31,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.7,
             "gust_kph": 22,
             "uv": 10
           },
           {
             "time_epoch": 1716217200,
             "time": "2024-05-20 18:00",
             "temp_c": 40.5,
             "temp_f": 104.8,
             "is_day": 1,
             "condition": {
               "text": "Sunny",
               "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
               "code": 1000
             },
             "wind_mph": 7.8,
             "wind_kph": 12.6,
             "wind_degree": 357,
             "wind_dir": "N",
             "pressure_mb": 1007,
             "pressure_in": 29.73,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 8,
             "cloud": 0,
             "feelslike_c": 40.6,
             "feelslike_f": 105,
             "windchill_c": 40.5,
             "windchill_f": 104.8,
             "heatindex_c": 40.6,
             "heatindex_f": 105,
             "dewpoint_c": -0.1,
             "dewpoint_f": 31.9,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 12.1,
             "gust_kph": 19.5,
             "uv": 10
           },
           {
             "time_epoch": 1716220800,
             "time": "2024-05-20 19:00",
             "temp_c": 36.9,
             "temp_f": 98.3,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 5.8,
             "wind_kph": 9.4,
             "wind_degree": 344,
             "wind_dir": "NNW",
             "pressure_mb": 1007,
             "pressure_in": 29.74,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 10,
             "cloud": 0,
             "feelslike_c": 35.5,
             "feelslike_f": 95.9,
             "windchill_c": 36.9,
             "windchill_f": 98.3,
             "heatindex_c": 35.5,
             "heatindex_f": 95.9,
             "dewpoint_c": 0.1,
             "dewpoint_f": 32.1,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 12.2,
             "gust_kph": 19.7,
             "uv": 1
           },
           {
             "time_epoch": 1716224400,
             "time": "2024-05-20 20:00",
             "temp_c": 35.7,
             "temp_f": 96.2,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 5.8,
             "wind_kph": 9.4,
             "wind_degree": 349,
             "wind_dir": "N",
             "pressure_mb": 1008,
             "pressure_in": 29.75,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 11,
             "cloud": 0,
             "feelslike_c": 34,
             "feelslike_f": 93.2,
             "windchill_c": 35.7,
             "windchill_f": 96.2,
             "heatindex_c": 34,
             "heatindex_f": 93.2,
             "dewpoint_c": 0.2,
             "dewpoint_f": 32.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 12.2,
             "gust_kph": 19.7,
             "uv": 1
           },
           {
             "time_epoch": 1716228000,
             "time": "2024-05-20 21:00",
             "temp_c": 35.2,
             "temp_f": 95.4,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 6.7,
             "wind_kph": 10.8,
             "wind_degree": 6,
             "wind_dir": "N",
             "pressure_mb": 1008,
             "pressure_in": 29.77,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 11,
             "cloud": 0,
             "feelslike_c": 33.5,
             "feelslike_f": 92.3,
             "windchill_c": 35.3,
             "windchill_f": 95.5,
             "heatindex_c": 33.5,
             "heatindex_f": 92.3,
             "dewpoint_c": 0.3,
             "dewpoint_f": 32.6,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 14.1,
             "gust_kph": 22.7,
             "uv": 1
           },
           {
             "time_epoch": 1716231600,
             "time": "2024-05-20 22:00",
             "temp_c": 34.3,
             "temp_f": 93.8,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 6.5,
             "wind_kph": 10.4,
             "wind_degree": 21,
             "wind_dir": "NNE",
             "pressure_mb": 1009,
             "pressure_in": 29.78,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 12,
             "cloud": 0,
             "feelslike_c": 32.4,
             "feelslike_f": 90.2,
             "windchill_c": 34.3,
             "windchill_f": 93.8,
             "heatindex_c": 32.4,
             "heatindex_f": 90.2,
             "dewpoint_c": 0.7,
             "dewpoint_f": 33.3,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 13.6,
             "gust_kph": 21.9,
             "uv": 1
           },
           {
             "time_epoch": 1716235200,
             "time": "2024-05-20 23:00",
             "temp_c": 32.9,
             "temp_f": 91.3,
             "is_day": 0,
             "condition": {
               "text": "Clear ",
               "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
               "code": 1000
             },
             "wind_mph": 4.9,
             "wind_kph": 7.9,
             "wind_degree": 36,
             "wind_dir": "NE",
             "pressure_mb": 1008,
             "pressure_in": 29.78,
             "precip_mm": 0,
             "precip_in": 0,
             "snow_cm": 0,
             "humidity": 13,
             "cloud": 0,
             "feelslike_c": 30.8,
             "feelslike_f": 87.4,
             "windchill_c": 32.9,
             "windchill_f": 91.3,
             "heatindex_c": 30.8,
             "heatindex_f": 87.4,
             "dewpoint_c": 1.1,
             "dewpoint_f": 33.9,
             "will_it_rain": 0,
             "chance_of_rain": 0,
             "will_it_snow": 0,
             "chance_of_snow": 0,
             "vis_km": 10,
             "vis_miles": 6,
             "gust_mph": 10.3,
             "gust_kph": 16.6,
             "uv": 1
           }
         ]
       }
     ]
   }
 }
 */
